using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Numerics;
using System.Runtime.InteropServices.WindowsRuntime;
using Cryptography_Toolkit.Components;
using Cryptography_Toolkit.Helpers;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Controls.Primitives;
using Microsoft.UI.Xaml.Data;
using Microsoft.UI.Xaml.Input;
using Microsoft.UI.Xaml.Media;
using Microsoft.UI.Xaml.Navigation;
using Windows.Foundation;
using Windows.Foundation.Collections;

// To learn more about WinUI, the WinUI project structure,
// and more about our project templates, see: http://aka.ms/winui-project-info.

namespace Cryptography_Toolkit.Pages;

/// <summary>
/// An empty page that can be used on its own or navigated to within a Frame.
/// </summary>
public sealed partial class AttacksDLPPage : Page
{
    public AttacksDLPPage()
    {
        InitializeComponent();
    }

    private void BabyStepGiantStepExecuteButton_OnClick(object sender, RoutedEventArgs e)
    {
        var shanksBabyStepGiantStepMethod = new Components.ShanksBabyStepGiantStepMethod();
        if (int.TryParse(BabyStepGiantStepOrderNumberBox.Text, out var order) &&
            int.TryParse(BabyStepGiantStepGeneratorNumberBox.Text, out var generator) &&
            int.TryParse(BabyStepGiantStepGroupElementNumberBox.Text, out var groupElement))
        {
            // var preCheck = shanksBabyStepGiantStepMethod.ShanksBabyStepGiantStepMethodPreCheck(order, generator, groupElement);
            // if (preCheck == 1)
            // {
            //     BabyStepGiantStepLogTextBox.Text = "Order n must be ≥ 2";
            //     BabyStepGiantStepStatusInfoBar.Severity = InfoBarSeverity.Error;
            //     BabyStepGiantStepStatusInfoBar.Message = "Please enter correct parameters.";
            // }
            // else if (preCheck == 2)
            // {
            //     BabyStepGiantStepLogTextBox.Text = "Generator α and order n must be coprime";
            //     BabyStepGiantStepStatusInfoBar.Severity = InfoBarSeverity.Error;
            //     BabyStepGiantStepStatusInfoBar.Message = "Please enter correct parameters.";
            // }
            // else if (preCheck == 3)
            // {
            //     BabyStepGiantStepLogTextBox.Text = "Group Element β is not in the cyclic subgroup generated by generator α";
            //     BabyStepGiantStepStatusInfoBar.Severity = InfoBarSeverity.Error;
            //     BabyStepGiantStepStatusInfoBar.Message = "Please enter correct parameters.";
            // }
            var result = shanksBabyStepGiantStepMethod.ShanksBabyStepGiantStepMethodRun(generator, groupElement, order);
            if (true)
            {
                var log = new System.Text.StringBuilder();
                
                log.AppendLine("========== Baby Steps & Giant Steps ==========");
                log.AppendLine($"{"x_b",6} | {"α^x_b mod n",15} || {"i",6} | {"β * α^(-i·t) mod n",20}");
                log.AppendLine(new string('-', 26) + "||" + new string('-', 30));

                int babyCount = result.BabySteps.Count;
                int giantCount = result.GiantSteps.Count;
                int maxRows = Math.Max(babyCount, giantCount);

                for (int row = 0; row < maxRows; row++)
                {
                    string left = row < babyCount
                        ? $"{result.BabySteps[row].Item1,6} | {result.BabySteps[row].Item2,15}"
                        : new string(' ', 6) + " | " + new string(' ', 15);
                    string right = row < giantCount
                        ? $"{result.GiantSteps[row].Item1,6} | {result.GiantSteps[row].Item2,20}"
                        : new string(' ', 6) + " | " + new string(' ', 20);
                    log.AppendLine($"{left} || {right}");
                }
                log.AppendLine();

                log.AppendLine($"Generator Inverse: {result.GeneratorInverse}");
                log.AppendLine($"t (⌈√n⌉): {result.T}");
                log.AppendLine(new string('=', 60));
                if (result.DiscreteLog.HasValue)
                    log.AppendLine($"Discrete Log x: {result.DiscreteLog.Value}");
                else
                    log.AppendLine("Discrete Log x: 未找到解");

                BabyStepGiantStepLogTextBox.Text = log.ToString();
            }
            else
            {
                BabyStepGiantStepLogTextBox.Text = "未能计算出结果。";
            }
        }
        else
        {
            BabyStepGiantStepLogTextBox.Text = "Please enter correct parameters.";
            BabyStepGiantStepStatusInfoBar.Severity = InfoBarSeverity.Warning;
            BabyStepGiantStepStatusInfoBar.Message = "Please enter correct parameters.";
        }
    }
}
